Integrated JSON and fixed the errors
wisemen-digital/nestjs-template pull request #2
Opened 2023-09-04 12:49 UTC by stephenhenckaerts

2023-09-04 14:18 UTC, jorenvandeweyer requested changes

2023-09-04 14:18 UTC, jorenvandeweyer commented on .eslintrc.json
lijkt me niet volledig

2023-09-04 14:18 UTC, jorenvandeweyer commented on ~/.nvim/undo/%Users%stephenhenckaerts%Documents%projects%nestjs%nestjs-template%.eslintrc.json
deze files mogen weg

2023-09-06 10:00 UTC, Kobe-Kwanten approved these changes

2023-09-06 13:01 UTC, jorenvandeweyer approved these changes

2023-09-06 13:05 UTC, closed without merging