Feature/refactor
wisemen-digital/nestjs-template pull request #6
Opened 2023-09-19 14:00 UTC by JonasVannieuwenhuijsen

2023-09-20 05:31 UTC, jorenvandeweyer requested changes

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/app.module.ts
> +        : `.env.${process.env.NODE_ENV}`
```
envFilePath: process.env.ENV_FILE
```

Default neemt die .env als de env variable undefined zou zijn

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/controllers/user.controller.ts
> +  ): Promise<UserTransformerType[]> {
Vreemde enter

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/pipes/user.pipe.ts
> +    }
Zou dit toch niet beter een guard zijn in nest js?

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/pipes/user.pipe.ts
> +      throw new HttpException('unauthorized', 403)
Forbidden error ipv unauthorized

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/pipes/user.pipe.ts
> +    const user = await this.userService.findOne(uuid)
User gaat in deze flow nu ook 2x gequeried worden uit de database 1x hier en 1x in de controller

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/auth/repositories/client.repository.ts
Welke meerwaarde heeft deze custom repository boven op de default repository? 

Hadden we deze file wel al moeten maken?

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/services/user.service.ts
> +    if (email === undefined || email === null) throw new HttpException('missing_parameters', 400)
email == undefined

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/services/user.service.ts
> +    if (user === null || user === undefined) throw new HttpException('not_found', 404)
user == null

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/tests/user.seeder.ts
> +    if (options?.save === true) {
Ik zou vanaf nu altijd default saven in seeder, als ge een dto wilt moet ge maar een createdto functir maken?

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/tests/user-seeder.module.ts
> +    })
Kan deze niet geimport worden?

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/modules/users/tests/user.e2e.test.ts
> +        SeederModule
Waarom inport ge niet alleen de seeder die ge nodig hebt? Zo weet ge zeer explixiet welke ge nodig zou hebben

2023-09-20 05:31 UTC, jorenvandeweyer commented on src/seeder.module.ts
Misschien overbodig?

2023-09-20 15:48 UTC, jorenvandeweyer approved these changes

2023-12-15 09:47 UTC, stephenhenckaerts approved these changes

2023-12-15 10:00 UTC, merged