Feature/global updates
wisemen-digital/nestjs-template pull request #7
Opened 2024-01-02 10:10 UTC by JonasVannieuwenhuijsen

2024-01-04 13:46 UTC, siemenvdn commented on .github/workflows/test.yaml
> +          POSTGRES_DB: 'easy_2_drop'
```suggestion
          POSTGRES_DB: 'test_db'
```

2024-01-04 13:47 UTC, siemenvdn commented on src/config/sql/utils/typeorm.ts
> +  if (type === 'false') return false
overbodig

2024-01-04 13:52 UTC, siemenvdn commented on src/main.ts
> +    .setDescription('The Easy2Drop API description')
kunnen we nie een `PROJECT_NAME` in de `.env` steken en die deze automatisch laten invullen?

2024-01-04 13:58 UTC, siemenvdn requested changes
ik ben zwaar tegen die `Api` decorators, gebruik de [nestjs cli-plugin](https://docs.nestjs.com/openapi/cli-plugin), die doet da allemaal automatisch

2024-01-09 09:32 UTC, jorenvandeweyer commented on src/config/sql/utils/typeorm.ts
> +  if (type === 'false') return false
dit lijkt me niet overbodig?

2024-01-09 09:53 UTC, JonasVannieuwenhuijsen commented on package.json
> +    "@sentry/types": "^7.91.0",
Moet node en tracing niet bij dependencies blijven staan en enkel types naar devDep.?

2024-01-09 10:26 UTC, jorenvandeweyer approved these changes

2024-01-09 10:26 UTC, jorenvandeweyer commented on package.json
> +    "@sentry/types": "^7.91.0",
ik denk dt ik hier mis was 🤔

2024-01-10 13:54 UTC, merged